# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'WEBMVC.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  - deployment: build
    displayName: Build
    environment: Build
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo This is a BUILD job
            displayName: 'Build project'
            
          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            inputs:
              restoreSolution: '$(solution)'


          - task: VSTest@2
            inputs:
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: DotNetCoreCLI@2
            inputs:
             command: 'test'
             projects: 'WEBMVCUnitTest/WEBMVCUnitTest.csproj'

- stage: CD
  displayName: CD Stage
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: Deploy
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo This is a BUILD job
            displayName: 'Build project'

          - task: PublishBuildArtifacts@1
            displayName: 'publish artifacts'